name: Deploy to Raspberry Pi

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy with Docker Compose
        run: |
          docker compose up -d --build
# rsync to be once implemented 